[package]
name = "uni-app"
version = "0.1.0"
authors = ["Edwin Cheng <edwin0cheng@gmail.com>"]

[dependencies]

[target.wasm32-unknown-unknown.dependencies]
stdweb =  "0.4.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = "0.15.0"
time = "0.1.39"

