[package]
name = "uni-glsl"
version = "0.1.0"
authors = ["Edwin Cheng <edwin0cheng@gmail.com>"]

[lib]
name = "uni_glsl"
path = "src/lib.rs"

[dependencies.lazy_static]
version = "1.0"

[dependencies.nom]
version = "4.0.0-alpha2"
default-features = false
features = ["std", "verbose-errors"]