[package]
name = "uni-pad"
version = "0.1.0"
authors = ["jice <jice.nospam@gmail.com>"]

[dependencies]
uni-app={git="https://github.com/unrust/uni-app"}
[target.wasm32-unknown-unknown.dependencies]
stdweb =  "0.4.8"
